import { doc, runTransaction } from "firebase/firestore";
import { db } from "./firebase";

export interface GajiPenguranganItem {
  id: string;
  nominal: number;
  ket: string;
  photoUrl?: string;
  dateStr?: string;
  _isAutoSistem?: boolean;
  _idempKey?: string;
}

export interface GajiTambahanItem {
  id: string;
  nominal: number;
  ket: string;
  status?: "belum" | "sudah";
}

export interface GajiMonthRecord {
  id: string;
  bulanTahun: string; // e.g. "08/26"
  gajiPokok: number;
  gajiTambahan: GajiTambahanItem[];
  gajiPengurangan: GajiPenguranganItem[];
  buktiTransfer?: string;
  ongkirBulanIni?: number;
  ongkirMasukGajiBulanIni?: number;
  dendaAbsen?: number;
  updatedAt?: number;
  isAutoGenerated?: boolean;
  [key: string]: any;
}

/**
 * Normalizes email string for consistent Firestore docId lookup.
 */
export function normalizeEmail(email: string): string {
  return (email || "").toLowerCase().trim();
}

/**
 * Atomically adds a penalty / deduction (denda) to an employee's salary record using Firestore Transaction.
 * Guarantees idempotency via `_idempKey` and never overwrites existing records or other deductions.
 */
export async function atomicAddDenda(
  email: string,
  dendaItem: GajiPenguranganItem,
  bulanTahun: string,
  fallbackBasePokok: number = 1500000
): Promise<{ success: boolean; alreadyExisted: boolean }> {
  const cleanEmail = normalizeEmail(email);
  if (!cleanEmail) throw new Error("Email pegawai tidak valid");

  const docRef = doc(db, "gaji_pegawai", cleanEmail);

  return await runTransaction(db, async (transaction) => {
    const snap = await transaction.get(docRef);
    let records: GajiMonthRecord[] = [];
    let basePokok = fallbackBasePokok;

    if (snap.exists()) {
      const data = snap.data();
      records = Array.isArray(data.records) ? [...data.records] : [];
      
      // Determine basePokok from existing records or doc
      for (const r of records) {
        const v = Number(r.gajiPokok) || 0;
        if (v > 0) {
          basePokok = v;
          break;
        }
      }
      if (basePokok === 0) {
        basePokok = Number(data.gajiPokok) || fallbackBasePokok;
      }
    }

    // Check if this deduction already exists in any month by idempotency key
    if (dendaItem._idempKey) {
      const alreadyExists = records.some((r) =>
        Array.isArray(r.gajiPengurangan) &&
        r.gajiPengurangan.some((pg) => pg._idempKey === dendaItem._idempKey)
      );
      if (alreadyExists) {
        return { success: true, alreadyExisted: true };
      }
    }

    const monthIndex = records.findIndex((r) => r.bulanTahun === bulanTahun);
    if (monthIndex >= 0) {
      const existingMonth = records[monthIndex];
      const existingPg = Array.isArray(existingMonth.gajiPengurangan)
        ? [...existingMonth.gajiPengurangan]
        : [];
      
      records[monthIndex] = {
        ...existingMonth,
        gajiPengurangan: [...existingPg, dendaItem],
        updatedAt: Date.now(),
      };
    } else {
      records = [
        {
          id: `rec-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
          bulanTahun,
          gajiPokok: basePokok,
          gajiTambahan: [],
          gajiPengurangan: [dendaItem],
          isAutoGenerated: true,
          updatedAt: Date.now(),
        },
        ...records,
      ];
    }

    transaction.set(
      docRef,
      {
        records,
        gajiPokok: basePokok,
        updatedAt: Date.now(),
      },
      { merge: true }
    );

    return { success: true, alreadyExisted: false };
  });
}

/**
 * Atomically saves an Owner's edited salary records for an employee.
 * Ensures that any real-time auto-penalties (`_isAutoSistem`) that occurred while the Owner was editing are preserved.
 */
export async function atomicSaveGaji(
  email: string,
  localRecords: GajiMonthRecord[],
  preferredGajiPokok?: number
): Promise<void> {
  const cleanEmail = normalizeEmail(email);
  if (!cleanEmail) throw new Error("Email pegawai tidak valid");

  const docRef = doc(db, "gaji_pegawai", cleanEmail);

  await runTransaction(db, async (transaction) => {
    const snap = await transaction.get(docRef);
    let dbRecords: GajiMonthRecord[] = [];
    let resolvedGajiPokok = preferredGajiPokok || 0;

    if (snap.exists()) {
      const data = snap.data();
      dbRecords = Array.isArray(data.records) ? data.records : [];
      if (resolvedGajiPokok === 0) {
        resolvedGajiPokok = Number(data.gajiPokok) || 1500000;
      }
    }

    if (resolvedGajiPokok === 0) {
      for (const r of localRecords) {
        const v = Number(r.gajiPokok) || 0;
        if (v > 0) {
          resolvedGajiPokok = v;
          break;
        }
      }
      if (resolvedGajiPokok === 0) resolvedGajiPokok = 1500000;
    }

    // Smart merge: Map local records and preserve any missing real-time DB auto-system deductions
    const mergedRecords = localRecords.map((localRec) => {
      const dbRec = dbRecords.find((dr) => dr.bulanTahun === localRec.bulanTahun);
      if (!dbRec) {
        return {
          ...localRec,
          gajiPokok: Number(localRec.gajiPokok) || resolvedGajiPokok,
        };
      }

      const localPg = Array.isArray(localRec.gajiPengurangan) ? localRec.gajiPengurangan : [];
      const dbPg = Array.isArray(dbRec.gajiPengurangan) ? dbRec.gajiPengurangan : [];

      // Collect all IDs / idempotency keys in local records
      const localKeySet = new Set<string>();
      localPg.forEach((p) => {
        if (p.id) localKeySet.add(p.id);
        if (p._idempKey) localKeySet.add(p._idempKey);
      });

      // Find auto-system items in DB that were added in the background
      const missingDbAutoItems = dbPg.filter(
        (p) =>
          p._isAutoSistem &&
          p._idempKey &&
          !localKeySet.has(p._idempKey) &&
          !localKeySet.has(p.id)
      );

      const combinedPg = [...localPg, ...missingDbAutoItems];

      return {
        ...localRec,
        gajiPokok: Number(localRec.gajiPokok) || resolvedGajiPokok,
        gajiPengurangan: combinedPg,
      };
    });

    // Also preserve any months that exist in DB but were not in localRecords
    const localMonthSet = new Set(localRecords.map((r) => r.bulanTahun));
    dbRecords.forEach((dbRec) => {
      if (!localMonthSet.has(dbRec.bulanTahun)) {
        mergedRecords.push(dbRec);
      }
    });

    // Sanitize numbers
    const sanitizedRecords = mergedRecords.map((r) => ({
      ...r,
      gajiPokok: Number(r.gajiPokok) || resolvedGajiPokok,
      gajiTambahan: (r.gajiTambahan || []).map((t) => ({
        ...t,
        nominal: Number(t.nominal) || 0,
      })),
      gajiPengurangan: (r.gajiPengurangan || []).map((p) => ({
        ...p,
        nominal: Number(p.nominal) || 0,
      })),
      updatedAt: Date.now(),
    }));

    transaction.set(
      docRef,
      {
        records: sanitizedRecords,
        gajiPokok: resolvedGajiPokok,
        updatedAt: Date.now(),
      },
      { merge: true }
    );
  });
}

/**
 * Atomically ensures an auto-generated month stub (e.g. for Ongkir) exists in the database.
 * Never overwrites existing months or deductions.
 */
export async function atomicEnsureGajiRecords(
  email: string,
  autoMonths: Array<{ bulanTahun: string; id: string }>,
  basePokok: number
): Promise<boolean> {
  const cleanEmail = normalizeEmail(email);
  if (!cleanEmail || autoMonths.length === 0) return false;

  const docRef = doc(db, "gaji_pegawai", cleanEmail);

  return await runTransaction(db, async (transaction) => {
    const snap = await transaction.get(docRef);
    let records: GajiMonthRecord[] = [];
    let currentBasePokok = basePokok;

    if (snap.exists()) {
      const data = snap.data();
      records = Array.isArray(data.records) ? [...data.records] : [];
      if (currentBasePokok === 0) {
        currentBasePokok = Number(data.gajiPokok) || 1500000;
      }
    }
    if (currentBasePokok === 0) currentBasePokok = 1500000;

    let modified = false;

    // Check repair for 0 gajiPokok
    records = records.map((r) => {
      if ((Number(r.gajiPokok) || 0) === 0 && r.isAutoGenerated) {
        modified = true;
        return { ...r, gajiPokok: currentBasePokok };
      }
      return r;
    });

    // Add missing months
    autoMonths.forEach((autoM) => {
      const alreadyExists = records.some((r) => r.bulanTahun === autoM.bulanTahun);
      if (!alreadyExists) {
        records.push({
          id: autoM.id,
          bulanTahun: autoM.bulanTahun,
          gajiPokok: currentBasePokok,
          gajiTambahan: [],
          gajiPengurangan: [],
          buktiTransfer: "",
          updatedAt: Date.now(),
          isAutoGenerated: true,
        });
        modified = true;
      }
    });

    if (modified) {
      transaction.set(
        docRef,
        {
          records,
          gajiPokok: currentBasePokok,
          updatedAt: Date.now(),
        },
        { merge: true }
      );
      return true;
    }

    return false;
  });
}
