import { Firestore, Transaction, runTransaction, getDocFromServer, DocumentReference } from 'firebase/firestore';
import { normalizeBulanTahun } from './absenPeriod';

// Object key order is not a data change (Firestore may reorder map keys).
export function sameSalaryValue(a: any, b: any): boolean {
  if (a === b) return true;
  if (!a || !b || typeof a !== 'object' || typeof b !== 'object') return false;
  if (Array.isArray(a) !== Array.isArray(b)) return false;
  const keys = Object.keys(a);
  return keys.length === Object.keys(b).length && keys.every(k => sameSalaryValue(a[k], b[k]));
}

// Rules can reject a revision before Firestore reports the transaction conflict.
// Retry ONLY if a server read confirms that the salary revision changed.
export async function runSalaryTransaction<T>(db: Firestore, callback: (tx: Transaction) => Promise<T>): Promise<T> {
  for (let attempt = 0; ; attempt++) {
    const reads = new Map<DocumentReference, number>();
    try {
      return await runTransaction(db, tx => callback(new Proxy(tx, {
        get(target, key) {
          if (key === 'get') return async (ref: DocumentReference) => {
            const snap = await target.get(ref);
            reads.set(ref, Number(snap.data()?.salaryRevision) || 0);
            return snap;
          };
          const value = Reflect.get(target, key);
          return typeof value === 'function' ? value.bind(target) : value;
        }
      })));
    } catch (error: any) {
      if (error?.code !== 'permission-denied' || attempt >= 3) throw error;
      let changed = false;
      for (const [ref, revision] of reads) {
        const snap = await getDocFromServer(ref);
        if ((Number(snap.data()?.salaryRevision) || 0) !== revision) changed = true;
      }
      if (!changed) throw error;
    }
  }
}

const key = (v: any) => String(v._idempKey || v.id);
const conflict = () => { throw new Error('Bagian gaji yang sama diubah di perangkat lain. Draf Anda tetap ada; periksa perubahan terbaru sebelum menyimpan.'); };
const value = (field: string, v: any) => field === 'nominal' || field === 'gajiPokok' ? Number(v) || 0
  : field === 'isDibatalkan' ? Boolean(v) : field === 'status' ? v || 'belum' : v ?? '';

function mergeFields(base: any, edit: any, remote: any, source: any, fields: string[]) {
  const result = { ...edit, ...remote };
  for (const field of fields) {
    if (sameSalaryValue(value(field, edit[field]), value(field, base?.[field]))) continue;
    if (remote && !sameSalaryValue(value(field, remote[field]), value(field, source?.[field]))
      && !sameSalaryValue(value(field, remote[field]), value(field, edit[field]))) conflict();
    result[field] = value(field, edit[field]);
  }
  return result;
}

function mergeItems(base: any[], edit: any[], remote: any[], source: any[]) {
  const fields = ['nominal', 'ket', 'status', 'isDibatalkan', 'photoUrl'];
  const result = remote.map(x => ({ ...x }));
  for (const item of edit) {
    const before = base.find(x => key(x) === key(item));
    const original = source.find(x => key(x) === key(item));
    const index = result.findIndex(x => key(x) === key(item));
    if (index < 0) {
      if (original) { if (!sameSalaryValue(before, item)) conflict(); continue; }
      result.push({ ...item, nominal: Number(item.nominal) || 0 });
    } else result[index] = mergeFields(before, item, result[index], original, fields);
  }
  return result.filter(item => {
    if (!base.some(x => key(x) === key(item)) || edit.some(x => key(x) === key(item))) return true;
    const original = source.find(x => key(x) === key(item));
    if (original && fields.some(f => !sameSalaryValue(value(f, original[f]), value(f, item[f])))) conflict();
    return false;
  });
}

export function mergeSalaryEdits(source: any[], baseline: any[], edited: any[], latest: any[]) {
  const find = (list: any[], r: any) => list.find(x => x.id === r.id)
    || list.find(x => normalizeBulanTahun(x.bulanTahun) === normalizeBulanTahun(r.bulanTahun));
  const result = latest.map(r => ({ ...r }));
  for (const edit of edited) {
    const base = find(baseline, edit);
    const original = find(source, base || edit);
    const remote = find(result, base || edit);
    if (!remote && original) { if (!sameSalaryValue(base, edit)) conflict(); continue; }
    const merged = mergeFields(base, edit, remote, original, ['gajiPokok', 'bulanTahun', 'buktiTransfer']);
    // Display-only totals must never be persisted from a filtered history view.
    const record = { ...(remote || {}), id: remote?.id || edit.id,
      bulanTahun: normalizeBulanTahun(merged.bulanTahun), gajiPokok: Number(merged.gajiPokok) || 0,
      buktiTransfer: merged.buktiTransfer || '', isAutoGenerated: false, updatedAt: Date.now(),
      gajiTambahan: mergeItems(base?.gajiTambahan || [], edit.gajiTambahan || [], remote?.gajiTambahan || [], original?.gajiTambahan || []),
      gajiPengurangan: mergeItems(base?.gajiPengurangan || [], edit.gajiPengurangan || [], remote?.gajiPengurangan || [], original?.gajiPengurangan || []) };
    if (remote) result[result.indexOf(remote)] = record; else result.push(record);
  }
  // Preserve unseen months; never infer deletion from an incomplete view.
  return result;
}
